ID, Password, 이름, 나이, 주소, 전화번호, 이메일을 가지고 있는 DB 테이블의  도메인 객체를 JAVA 코드로 구현
Bill2Market/Bill2Market pull request #6
Opened 2022-03-25 11:54 UTC by seojeongyoon

완료했습니다.

2022-03-25 13:29 UTC, YoungSeokHong requested changes

2022-03-25 13:29 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/java/com/example/demo/model/Client.java
> +    private int trustpoint;
고생하셨습니다! 큰건 아니고 굉장히 사소한 이슈로 ```@Column(nullable = false)``` 대신에 ```@NotNull```을 쓰시면 어떨지 서정님 의견 듣고 싶습니다! ```@NotNull```이 서버에서 예외를 잡을 수 있어서 조금더 유리한 걸로 알고 있습니다.
읽었던 자료 첨부 합니다! https://kafcamus.tistory.com/15
추가적으로 ```trustpoint```가 의도한 뜻이 "trust point"라면 ```trust_point```로 수정하시는 것이 더 좋을 것 같습니다!

2022-03-26 08:31 UTC, seojeongyoon commented on bill2_spring_boot/src/main/java/com/example/demo/model/Client.java
> +    private int trustpoint;
의견 감사드립니다!

데이터베이스 수정과 어노테이션 변경 완료했습니다.

2022-03-27 07:33 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/java/com/example/demo/model/Client.java
> +    private int trustpoint;
DB에 추가적으로 Enum 타입의 Role 하나만 추가 부탁드립니다.
```java

    @Column
    @Enumerated(EnumType.STRING)
    private Role role;
```
이 컬럼을 하나 더 추가할 예정입니다

2022-03-27 12:35 UTC, YoungSeokHong approved these changes
고생하셨습니다!

2022-03-27 12:36 UTC, merged