Taeyeong
Bill2Market/Bill2Market pull request #7
Opened 2022-03-26 06:16 UTC by TaeYeongKwak

**로그인 서버로직 구현**
jwt를 통한 로그인 로직 구현하였습니다. 현재 api 룰이 정해지지 않아서 임시로 url과 api 인터페이스 정하였습니다.
또한 client 테이블이 어떻게 생겼는지 확실히 알지 못해서 일단 client_test라는 이름으로 임시 테이블을 생성하여 test 해보았습니다.

2022-03-26 20:23 UTC, YoungSeokHong requested changes

2022-03-26 20:23 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/java/com/example/demo/controller/AuthController.java
> +}
다 너무 좋은 코드인데 33번 라인에 ```orElseThrow(ClientNotFoundException::new)```부분에서 개발자 입장으로 봤을 때 어느 오류가 나건 ```ClientNotFoundException```이 나와서 디버깅이 어려울 것 같아서 혹시 상황에 따라서 Exception 처리가 다르게 되게 할 수 있을까요?

잘 몰라서 드리는 질문입니다 ㅠㅠ 무리라고 판단하시거나 필요없다고 판단하시면 굳이 신경 안쓰셔도 됩니다!

2022-03-26 20:23 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/resources/application.properties
> +spring.datasource.password=12345678
Postman으로 API 검사해보는데 DB 접근이 제대로 안되는 것 같아서ㅠㅠ 찾아봤는데 왠지 이 부분 문제일 것 같습니다. 한번 확인 부탁드립니다!
평소에 저는 mybatis나 jdbc쓸 때 포트번호와 ```serverTimeZone``` ```useSSL```설정도 해줬었는데 이상황에서는 불필요한지 궁금합니다.

2022-03-26 20:23 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/resources/application.properties
> +spring.jwt.expiration=3600000
아주 마이너한 이슈인데 토큰 만기시간을 ```1*60*60*1000```과 같이 기록해두면 좀 더 시간을 보기 편할 것 같습니다!

2022-03-26 20:23 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/java/com/example/demo/model/client/ClientPrincipal.java
> +package com.example.demo.model.client;
client와 clientPrincipal을 따로 두시는 이유가 있을까요?

2022-03-27 02:08 UTC, TaeYeongKwak commented on bill2_spring_boot/src/main/resources/application.properties
> +spring.jwt.expiration=3600000
1*60*60*1000 형식으로 둘 경우, @Value 어노테이션으로 해당 값을 읽어올때 String 값으로 읽게 되어서 어쩔 수 없이 3600000으로 표시하였습니다. 일단 윗줄에 주석을 통해 1*60*60*1000 이라고 적어두도록 하겠습니다.

2022-03-27 02:25 UTC, TaeYeongKwak commented on bill2_spring_boot/src/main/java/com/example/demo/model/client/ClientPrincipal.java
> +package com.example.demo.model.client;
후에 sns 로그인을 구현할 때 유저정보를 담은 클래스에 UserDetails, OidUser, OAuth2User 등의 클래스를 상속받아야합니다. 기존에 존재하는 client에 모두 상속받아 사용해도 되겠지만 개인적으로 entity 클래스는 entity 클래스의 역할만 하는 것이 나을 것이라고 생각하여 해당 클래스들을 상속받은 clientPrincipal 이라는 클래스를 새로 만들기로 하였습니다.

2022-03-27 02:53 UTC, TaeYeongKwak commented on bill2_spring_boot/src/main/java/com/example/demo/controller/AuthController.java
> +}
아마 각 상황에 따라 if문으로 처리하면 가능할 것 같습니다. 필요한 Exception을 알려주시면 상황별로 다른 Exception이 발생하도록 해보겠습니다.

2022-03-27 03:47 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/resources/application.properties
> +spring.jwt.expiration=3600000
아 그렇군요 ㅠㅠ 네넵 감사합니다!

2022-03-27 04:20 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/java/com/example/demo/model/client/ClientPrincipal.java
> +package com.example.demo.model.client;
네넵 이해했습니다! 감사합니다!

2022-03-27 04:42 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/java/com/example/demo/controller/AuthController.java
> +}
client_id가 없을 때 뜨는 Exception과 DB에 접근하다 실패 했을 때 뜨는 Exception이 구분이 됐으면 합니다.
```UnknownHostException``` 상황만 따로 하나 뺴주시면 될 것 같습니다!

2022-03-27 07:28 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/resources/application.properties
> +spring.datasource.password=12345678
DB테이블 문제였던 것 같습니다. swagger로 테스트하고 무사히 동작하는 것 확인했습니다!

2022-03-27 07:31 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/java/com/example/demo/model/client/Client.java
> +    private Role role;
다른 부분은 제대로 동작하는 것 확인했습니다! 고생하셨습니다 ㅠㅠ
이 부분만 
```JAVA
@Entity(name="Client")
public class Client {
    @Id
    private String client_id;
    @Column(nullable = false)
    private String password;
    private String name;
    private String nickname;
    private String address;
    private String email;
    private String phone_number;
    private int age;
    private int trust_point;
    @Column
    @Enumerated(EnumType.STRING)
    private Role role;
}
```
로 수정해주시면 될 것 같습니다!

2022-03-27 12:06 UTC, YoungSeokHong approved these changes
고생하셨습니다!

2022-03-27 12:23 UTC, mi2ntae approved these changes
정말 고생 많으셨습니다

2022-03-27 13:00 UTC, YoungSeokHong commented on bill2_spring_boot/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto = create-drop
이 부분만 해결되면 merge하겠습니다!

2022-03-27 14:42 UTC, TaeYeongKwak commented on bill2_spring_boot/src/main/java/com/example/demo/advice/ExceptionAdvice.java
> +
아 복사 붙여넣기 하다가 실수로 안바꿨나보네요 다시 바꿔놓겠습니다.

2022-03-27 14:45 UTC, TaeYeongKwak commented on bill2_spring_boot/src/main/java/com/example/demo/service/ResponseService.java
> +        result.setSuccess(true);
네 삭제하도록 하겠습니다.

2022-03-27 14:45 UTC, TaeYeongKwak commented on bill2_spring_boot/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto = create-drop
네 아마 최근 commit 에서는 none으로 했던거 같은데 반영이 안되어있나보네요 다시 확인해서 올리도록 하겠습니다.

2022-03-27 15:22 UTC, merged